### ISSUE TITLE
-c or --config option as configuration support

### ISSUE THREAD

**Issue by cychu42** [mnosov622/simple-ssg1#5]
Hello, I wish to add the `-c` or `--config` option for this tool.

The `-c` or `--config` option would take a JSON config file path to accept configuration over other overlapping options. It will ignore unsupported configurations and replace missing ones with default value.
If any, user will be notified of an error.

**Comment by Maxn533** [comment]
Hi !

Sure, go ahead :)

**Comment by mnosov622** [comment]
Hi !

Sure, go ahead :)
